---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkins-app1
  namespace: default
  labels:
    app: jenkins-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-app1
  template:
    metadata:
      labels:
        app: jenkins-app1
    spec:
      containers:
      - name: jenkins-app1
        image: "lyday25/jenkins-pythonimg:latest"
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-app1
  namespace: default
spec:
  selector:
    app: jenkins-app1
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 5000
    port: 80
